# MySQL Configuration used for Autolab Docker Deployments
production:
  adapter: mysql2
  database: autolab_development
  pool: 5
  username: user1
  password: '123456'
  socket: /tmp/mysql.sock
  host: localhost
  variables:
    sql_mode: NO_ENGINE_SUBSTITUTION
